### ISSUE TITLE
error while installing plugin

### ISSUE THREAD

**Issue by BobbySlope** [kuestess/homebridge-platform-insteonlocal#81] opened 2019-12-10 07:22 UTC
npm
 ERR! code
 ENOENT
npm
 ERR!
syscall
 spawn git
npm ERR! path
 git
npm
 ERR!
errno
 ENOENT
npm
 ERR!
enoent
 Error while executing:
npm
ERR!
enoent
 undefined ls-remote -h -t ssh://git@github.com/automategreen/home-controller.git
npm ERR!
enoent
npm
ERR!
enoent
npm
ERR!
enoent
 spawn git ENOENT
npm
ERR!
enoent This is related to npm not being able to find a file.
npm
ERR!
 enoent
npm ERR!
 A complete log of this run can be found in:
npm ERR!
     /home/hoobs/.npm/_logs/2019-12-10T07_18_24_627Z-debug.log
[12/10/2019, 08:18:24] Installed "homebridge-platform-insteonlocal" package.

**Comment by kuestess** [comment] 2019-12-10 22:36
@BobbySlope Can you provide the command that produced the output above?  At first glance, this looks like an npm error - it can't seem to find the `home-controller` package.  You might try re-running `npm -g install homebridge-platform-insteonlocal`.  If that doesn't work, try manually installing the `home-controller` package by cloning from github and then doing `npm -g install` in the cloned directory.

**Comment by kwalb** [comment] 2019-12-17 02:39
This error is likely a hoobs install which doesn't install git by default

**Comment by kwalb** [comment] 2019-12-18 04:31
On a clean install of Hoobs utilizing the command you note above via ssh I am getting the same error:
`hoobs@hoobs:~ $ sudo npm -g install homebridge-platform-insteonlocal
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/automategreen/hom                               e-controller.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-18T04_30_04_938Z-debug.log
hoobs@hoobs:~ $ sudo npm -g install homebridge-platform-insteonlocal
`

**Comment by kwalb** [comment] 2019-12-18 04:36
Update: sudo npm install home-controller does install the home-controller package successfully, but installing insteonlocal still fails with the same error noted above

**Comment by kuestess** [comment] 2019-12-18 15:02
@kwalb @BobbySlope Maybe a few things to try.  First, try `sudo apt-get install git` - once that completes, try to install the plugin again using `npm -g install homebridge-platform-insteonlocal`.  If that doesn't work, then try downloading a zip of the repo from the front page, unzip it, change into the decompressed directory, and then run `npm -g install`.  Trying to narrow down where the issue is - hopefully one of those will work.

**Comment by kwalb** [comment] 2019-12-18 17:29
@kuestess Installing Git does allow the InsteonLocal package to install but it then proceeds to corrupt the Hoobs / Homebridge instance.

This error appears in Log, the homebridge instance stops responding and even after removing the InsteonLocal package this same error persists in the log until a full clean fresh installation of Homebridge is done

[Homebridge] [12/17/2019, 22:07:16] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 97b5c7b9-2a06-4755-839a-1626187aef75
[Homebridge] at Bridge.Accessory.addBridgedAccessory (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:268:13)
[Homebridge] at Server._configCachedPlatformAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:407:22)
[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:85:10)
[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:82:12)
[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:17:22)
[Homebridge] at Module._compile (internal/modules/cjs/loader.js:959:30)
[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
[Homebridge] at Module.load (internal/modules/cjs/loader.js:815:32)
[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:727:14)
[Homebridge] at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[Homebridge] at internal/main/run_main_module.js:17:11
[List Accessories] connect ECONNREFUSED 127.0.0.1:51515
[List Accessories] connect ECONNREFUSED 127.0.0.1:51515

**Comment by kuestess** [comment] 2019-12-18 20:56
@kwalb Interesting....  The UUID error is usually when you have two devices with the same name.  Does it work installing with just `npm -g install homebridge-platform-insteonlocal`?  I made a change in the package.json that should hopefully avoid the git error.

**Comment by kwalb** [comment] 2019-12-19 02:07
Created a mirror of my homebridge so I could have a test bed for fixing this plugin (as I've got a lot of Insteon devices so I'm personally invested in helping any way I can)

On a fresh install trying it via the Hoobs interface or via ssh I get the same error as the original bug:
[Homebridge] [12/18/2019, 21:02:36] Got SIGINT, shutting down service...npmERR!code ENOENT
npm ERR!syscall spawn git
npm ERR! path gitnpm ERR! errno ENOENTnpm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/automategreen/home-controller.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENTnpm ERR! enoent This is related to npm not being able to find a file.
npm ERR!enoentnpm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2019-12-19T02_02_42_986Z-debug.log[12/18/2019, 21:02:43] Installed "homebridge-platform-insteonlocal" package.

**Comment by kwalb** [comment] 2019-12-19 02:09
After installing git manually and trying an install again I get this error instead

hoobs@hoobs:~ $ sudo npm -g install homebridge-platform-insteonlocal
npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b master git://github.com/automategreen/home-controller.git /root/.npm/_cacache/tmp/git-clone-44a4859d
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-44a4859d': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-19T02_09_23_639Z-debug.log

**Comment by kwalb** [comment] 2019-12-19 04:05
Sorry forgot to tag you on the notes above @kuestess

**Comment by kuestess** [comment] 2019-12-19 13:56
@kwalb Thanks for doing all of this testing and bearing with me in this.  Pushed a minor update - ca you try `npm -g install homebridge-platform-insteonlocal` again on whatever your cleanest testbed is?

**Comment by kwalb** [comment] 2019-12-19 20:47
My testbed has been a fresh install of Hoobs 3.1.1 - (hoobs.org, "Homebridge-out-of-the-box"), which I believe was also @BobbySlope's platform.

Do get a couple errors during the installation when done manually like this.
```

hoobs@hoobs:~ $ sudo npm -g install homebridge-platform-insteonlocal
npm WARN deprecated spark@1.1.1: Use particle-api-js instead

> serialport@6.2.2 install /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
> prebuild-install || node-gyp rebuild

prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.13.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport/.node-gyp'
gyp ERR! System Linux 4.19.75-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-platform-insteonlocal/node_modules/serialport
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN notsup Unsupported engine for spark@1.1.1: wanted: {"node":"^0.10.26"} (current: {"node":"12.13.1","npm":"6.13.1"})
npm WARN notsup Not compatible with your version of node/npm: spark@1.1.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@6.2.2 (node_modules/homebridge-platform-insteonlocal/node_modules/serialport):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: serialport@6.2.2 install: `prebuild-install || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ homebridge-platform-insteonlocal@0.4.4-1
added 109 packages from 104 contributors in 22.842s
```

However, the good news, when installing the plugin via the console in Hoobs I am now getting full integration and functionality again. Your latest push appears to have fixed the compatibility issues.

**Comment by kuestess** [comment] 2019-12-19 21:18
@kwalb Great!  Thanks for testing.  Appears that it can't handle dependencies from GitHub, and installing git creates problems.  Serialport always seems to cause problems, but its not an issue unless you are using a PLM.  From the output above, it appears to be a permissions related issue, so something likely HOOBS specific.  You can ignore the `spark` error - its a dependency of `home-controller` that is only used if you leverage their spark/particle Insteon solution.  Closing this issue - feel free to re-open if you have issues.

**Closed by kuestess** 2019-12-19 21:18 UTC
